# Generated by Django 6.0 on 2026-01-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobeligibilityanalysis',
            name='interview_questions',
            field=models.JSONField(default=list, help_text='Technical interview questions tailored to this job with detailed answers'),
        ),
    ]
